\set ON_ERROR_STOP on
BEGIN;
SET LOCAL statement_timeout = 0;

CREATE TEMP TABLE sidt_raw (
  id_data_badan_usaha TEXT,
  nik_pengusaha TEXT,
  nama_pengusaha TEXT,
  nib TEXT,
  jenis_kelamin TEXT,
  is_disabilitas TEXT,
  tanggal_lahir TEXT,
  pendidikan_formal TEXT,
  kontak_hp TEXT,
  prov_pengusaha TEXT,
  kab_pengusaha TEXT,
  kec_pengusaha TEXT,
  kel_pengusaha TEXT,
  alamat_pengusaha TEXT,
  rt_pengusaha TEXT,
  rw_pengusaha TEXT,
  nama_usaha TEXT,
  kegiatan_utama TEXT,
  produk_utama TEXT,
  kategori_kbli TEXT,
  kode_kbli TEXT,
  status_badan_usaha TEXT,
  skala_usaha TEXT,
  modal_pendirian TEXT,
  bulan_mulai_operasi TEXT,
  tahun_mulai_operasi TEXT,
  omzet_tahunan TEXT,
  asset TEXT,
  prov_usaha TEXT,
  kab_usaha TEXT,
  kec_usaha TEXT,
  kel_usaha TEXT,
  alamat_usaha TEXT,
  rt_usaha TEXT,
  rw_usaha TEXT,
  foto_usaha TEXT,
  alamat_latitude TEXT,
  alamat_longitude TEXT,
  tk_dibayar_laki TEXT,
  tk_dibayar_perempuan TEXT,
  tk_dibayar_disabil_laki TEXT,
  tk_dibayar_disabil_perempuan TEXT,
  tk_not_dibayar_laki TEXT,
  tk_not_dibayar_perempuan TEXT,
  tk_not_dibayar_disabil_laki TEXT,
  tk_not_dibayar_disabil_perempua TEXT,
  pulled_at TEXT,
  updated_at TEXT,
  source_page TEXT
) ON COMMIT DROP;

COPY sidt_raw FROM STDIN WITH (FORMAT csv, HEADER true);
