const assert=require("node:assert/strict"); const test=require("node:test"); const extension=require("../src/index.js"); const ROLE="7d6d493c-1a6d-4c59-9e74-40d42a7862eb";
function router(){const routes={};return {routes,get:(p,h)=>routes[`GET ${p}`]=h,post:(p,h)=>routes[`POST ${p}`]=h};}
function response(){return {statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},set(k,v){this.headers[k]=v;},status(c){this.statusCode=c;return this;},json(v){this.body=v;}};}
async function run(handler,req={accountability:{user:"u",role:ROLE},query:{},body:{}}){const res=response();let error;handler(req,res,(e)=>{error=e;});for(let i=0;i<10&&!res.body&&!error;i++) await new Promise(r=>setImmediate(r));return {res,error};}
test("all routes reject anonymous and wrong role before DB",async()=>{let calls=0;const r=router();extension.handler(r,{database:{raw:async()=>{calls++;}},logger:{error(){}}});for(const [method,path] of [["GET","/metadata"],["GET","/metadata/options"],["GET","/templates"],["GET","/status"],["POST","/query"],["POST","/records"],["POST","/exports"],["GET","/exports/:jobId"],["GET","/exports/:jobId/download"]]){let out=await run(r.routes[`${method} ${path}`],{query:{},body:{}});assert.equal(out.error.statusCode,401,path);out=await run(r.routes[`${method} ${path}`],{accountability:{user:"u",role:"other"},query:{},body:{}});assert.equal(out.error.statusCode,403,path);}assert.equal(calls,0);});
test("Application User can read metadata and templates",async()=>{const r=router();extension.handler(r,{database:{raw:async()=>({rows:[{id:"field",semantic_id:"kota_nama",label:"Kota",field_group:"analytics",sort_order:1,semantic_role:"dimension",data_type:"text",lifecycle_status:"active",privacy_class:"aggregate",aggregation_capabilities:["group"],schema_version:1}]})},logger:{error(){}}});let out=await run(r.routes["GET /metadata"]);assert.equal(out.res.body.schemaVersion,1);out=await run(r.routes["GET /templates"]);assert.equal(out.res.body.templates[0].workforce.enabled,false);});

test("profile validates UUID and returns only masked semantic sections",async()=>{let calls=0;const r=router();extension.handler(r,{database:{raw:async()=>{calls++;return {rows:[{usaha_id:"11111111-1111-4111-8111-111111111111",status:"active",nama:"Usaha Canari",skala:"micro",masked_nik:"************1234",masked_phone:"08******1234",owner_name:"Pemilik",age_band:"25–34",omzet_quality:"reported",aset_quality:"missing",omzet_tahunan:987654321,total_aset:null,extra_fields:{aman:"x",nik_raw:"1234567890123456"},data_as_of:"2026-08-17T00:00:00Z"}]};}},logger:{error(){}}});let out=await run(r.routes["GET /umkm/:id"],{accountability:{user:"u",role:ROLE},params:{id:"bad"}});assert.equal(out.res.statusCode,404);assert.equal(calls,0);out=await run(r.routes["GET /umkm/:id"],{accountability:{user:"u",role:ROLE},params:{id:"11111111-1111-4111-8111-111111111111"}});assert.equal(out.res.statusCode,200);const text=JSON.stringify(out.res.body);assert.equal(text.includes("1234567890123456"),false);assert.equal(text.includes("987654321"),false);assert.equal(text.includes("raw"),false);assert.equal(out.res.body.data.actions.canArchive,true);});

test("download signatures are expiring and tamper resistant",async()=>{const {signDownload,verifyDownload}=require("../src/exports-service.js");const expiry=Date.now()+60000;const sig=signDownload("job","owner",expiry);assert.equal(verifyDownload("job","owner",expiry,sig),true);assert.equal(verifyDownload("job","other",expiry,sig),false);assert.equal(verifyDownload("job","owner",Date.now()-1,sig),false);});
